### ISSUE TITLE
Is it possible to get the location of the car from the API?

### ISSUE THREAD

**Issue by esbenr** [skagmo/ha_vwid#13]
It would really be neat if the sensor was a device_tracker with the cars current longitude and latitude. Then you can automate on home and not_home.
And then all the attributes should be on that.
So basically change the device_class of the sensor to a device_tracker and add the location if it's available in the API.

**Comment by skagmo** [comment]
Sorry, the We Connect ID API offers no position, otherwise it would definitely have been in this component. Apparently it's made unavailable for privacy reasons, but it doesn't make sense as the We Connect API (used for e-Golf etc.) has position.

**Comment by esbenr** [comment]
OK. Let's hope it will come in the future.
In Denmark Volkswagen has a third-party ODBC dongle that provides data to an app called MyVolkswagen.
I have that installed in my ID.4 too and that provides location and excessive historical data and statistics on trips.
I have made a node-red flow that pulls the API from this (connectedcars.io) and made a conjunction of the data from the two, for now.

Thanks for your feedback.
