### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by mawright89** [skagmo/ha_vwid#15]
Hi, really keen to get your integration setup but when I try and select the integration it says config flow could not be loaded. Any help would be appreciated.

**Comment by skagmo** [comment]
Do you have any more logs from Home Assistant you could share?

**Comment by mawright89** [comment]
thanks for the response. tried again and it worked. must have been my mistake. thanks for the good work, love this addition to my HASSIO setup.
