### ISSUE TITLE
Toggle charging with this integration?

### ISSUE THREAD

**Issue by CaptInsano** [skagmo/ha_vwid#16]
Firstly: many thanks to the dev for working on this project.

I have this integration setup and I can see my state of charge entity along with the following atrributes:

```
Vin
CurrentSOCPct 
CruisingRangeElectricKm
RemainingChargingTimeToCompleteMin
ChargingState
ChargeMode
ChargePowerKW
ChargeRateKmph
MaxChargeCurrentAC
AutoUnlockPlugWhenCharged
TargetSOCPct
PreferredChargeMode
PlugConnectionState
PlugLockState
RemainingClimatisationTimeMin
ClimatisationState
TargetTemperatureC
TargetTemperatureF
UnitInCar
ClimatisationWithoutExternalPower
ClimatizationAtUnlock
WindowHeatingEnabled
ZoneFrontLeftEnabled
ZoneFrontRightEnabled
TargetTemperatureK
TimeInCar
CarType
TotalRangeKm
```

Is it possible to change any of these attributes via the integration?

A switch to enable/disable changing would be brilliant.

**Comment by skagmo** [comment]
It is not implemented, but it's one of the top requested features, so it would be the first thing I'll look at adding if I get the time to do it.
