### ISSUE TITLE
State: ”unavailable”

### ISSUE THREAD

**Issue by PerWallentin** [skagmo/ha_vwid#17]
Thank you for a excellent work. I have one ID3 and one ID4 and it worked fine for two weeks to read data into node red but suddenly I do not get any information from my ID3. The car is online and I haven’t changed anything. Do you have any idea of what is failing? See enclosed picture. Object 0 is ID4 and object 1 is ID3.
![169B3824-42E1-414C-9C3F-BAE707D3F227](https://user-images.githubusercontent.com/70509423/149651024-998419b7-0d3a-41f0-a625-3c3bbb06afb9.jpeg)

**Comment by jonasbkarlsson** [comment]
Can you control your ID3 with the VW app?

**Comment by PerWallentin** [comment]
Hello,

yes, I can control the ID3 from WeConnect ID application. I have changed some setting and it works.

With best regards
Per

**Comment by PerWallentin** [comment]
I have two cars in the same integration. Is it only possible to have one car connected?
![92A65252-8DF3-40F4-81C6-A4856D8B0F5A](https://user-images.githubusercontent.com/70509423/150278864-6b67afc6-0452-4ef6-8f66-77d418f44d32.jpeg)

**Comment by skagmo** [comment]
Hi Per. I think you are the first to use two instances of the component/two cars. It's not designed for that, but I can put it on a list of feature requests.

**Comment by PerWallentin** [comment]
Hi! OK, thank you very much! Shall I do anything at this moment, like call or write to VW or is this not an issue for them?

**Comment by skagmo** [comment]
@PerWallentin There's nothing VW can do at this point, it's just something that needs to be implemented in this component. Thanks though.

**Comment by PerWallentin** [comment]
Now it worked 🤩
![A555E66C-161B-4682-8736-AAB5580E1911](https://user-images.githubusercontent.com/70509423/152695765-ce476b7f-6a28-4f5a-b6b0-00ecb6458a0a.jpeg)
