### ISSUE TITLE
configuration ok but entities wan't update

### ISSUE THREAD

**Issue by mauromognon** [skagmo/ha_vwid#18]
Hi, i have just configured all the entities, i can see the values of them (maybe the values fetched during the initialization of the add-on); but now for example if i turn on the heater with the vw connet id app, the entity in my HA doesn't update. I tried to wait some minutes but no updates are coming...; how much time is necessary fo the entities to update? how often does the add-on fetch the data?

thanks a lot...

Mauro

**Comment by skagmo** [comment]
The component updates every 10 minute. Could probably reduce it a bit, but I just went for a conservative number to be nice on the VW servers.
