### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by strutings** [skagmo/ha_vwid#19]
`Jan 28 15:29:15 homeassistant hass[11877]: 2022-01-28 15:29:15 INFO (MainThread) [homeassistant.setup] Setting up vwid
Jan 28 15:29:15 homeassistant hass[11877]: 2022-01-28 15:29:15 INFO (MainThread) [homeassistant.setup] Setup of domain vwid took 0.0 seconds
Jan 28 15:29:15 homeassistant hass[11877]: 2022-01-28 15:29:15 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.vwid
Jan 28 15:29:15 homeassistant hass[11877]: 2022-01-28 15:29:15 INFO (MainThread) [custom_components.vwid.libvwid] Reconnecting
Jan 28 15:29:16 homeassistant hass[11877]: 2022-01-28 15:29:16 ERROR (MainThread) [homeassistant.components.sensor] vwid: Error on device update!
Jan 28 15:29:16 homeassistant hass[11877]:   File "/home/homeassistant/.homeassistant/custom_components/vwid/sensor.py", line 92, in async_update
Jan 28 15:29:16 homeassistant hass[11877]:   File "/home/homeassistant/.homeassistant/custom_components/vwid/libvwid.py", line 156, in get_status
Jan 28 15:29:16 homeassistant hass[11877]:   File "/home/homeassistant/.homeassistant/custom_components/vwid/libvwid.py", line 62, in reconnect
Jan 28 15:29:16 homeassistant hass[11877]:   File "/home/homeassistant/.homeassistant/custom_components/vwid/libvwid.py", line 28, in form_from_response
`
Unable to connect from today.. tried to install and reinstall app, but seems like there is a connection issue with libvwid.py. Ios app is working as normal

**Comment by vantech14** [comment]
Same issue - reinstalled several times and won't connect.

**Comment by skagmo** [comment]
Seeing the same issue here, stopped updating two hours ago. Seems like there is a small change in the login page or API. I will probably have time to have a look at it tomorrow.

**Comment by strutings** [comment]
@tillsteinbach has got a quick fix in his repo now.

**Comment by skagmo** [comment]
@strutings Thanks for the heads up. Inspired by his fixes I did something similar. Pushed right to main as the component was broken at this point anyways. Works on my side. Please report back if it works or not.

**Comment by vantech14** [comment]
Worked for me. Thanks!

**Comment by strutings** [comment]
works like a charm. Thanks
