### ISSUE TITLE
No attributes available after Upgrade to Home Assistant 2022.4.0

### ISSUE THREAD

**Issue by tmakowka** [skagmo/ha_vwid#25]
After upgrading my setup to 2022.4.0, all attributes are not available any more.

Therefore i'm only able to use the SOC value which sits directly on the sensor value. All attributes are gone.

I can't find anything specific in the logs, has anyone encountered this also?

**Comment by confucius78** [comment]
Yep same here. SoC seems to update fine but no attributes

**Comment by pwcutajar** [comment]
Hi I also am having this issue, also deleting the integration and re installing is a bad idea as i now get success but no entity at all. Doesn't matter what credentials i put in the setup page.

**Comment by skagmo** [comment]
Hi. Haven't updated to 2022.4.0 yet, I will probably have time to update and take a look at this issue this weekend.

**Comment by pwcutajar** [comment]
Thanks so much

Well done on the great integration by the way

**Comment by nunocardosonuc** [comment]
Thank you so much.

**Comment by skagmo** [comment]
Should be fixed now, please verify. It was a tiny change in naming in Home Assistant.

**Comment by dewoert** [comment]
Working again.
Thanks for the quick fix!

**Comment by tmakowka** [comment]
Working for me also, thanks for fixing so quick!

**Comment by nunocardosonuc** [comment]
Working again.
Thank you for the quick fix!
