### ISSUE TITLE
Offline?

### ISSUE THREAD

**Issue by Hobjersgarden** [skagmo/ha_vwid#33]
I have problem with this intregation a cupple days I can't receive info from my id3

**Comment by javierivi** [comment]
I have the same problems from 2 days ago

**Comment by Beaker73** [comment]
And I have the same issue. Tried restarting, but HA tells me that the whole State of Charge sensor is not available anymore. (Red icon with tooltip restored)

**Comment by skagmo** [comment]
I've heard that multiple users has been required to log in and accept updated terms on myvolkswagen.net. Can you try that?

**Comment by Beaker73** [comment]
This indeed helped for me.
After logging in and accepting the terms, the data was available again (after I restarted my HA).

**Comment by Hobjersgarden** [comment]
It works again after i login and accept the terms on the webbside. Thanks :0)

**Comment by jcsogo** [comment]
I got the error below. I have logged in myvolkswagen.de and myvolkswagen.es and accepted the terms, but still the same error appears.

```
Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 47, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

**Comment by javierivi** [comment]
I had the problem of losing the integration in home assistant, but accepting the terms of the Volkswagen again worked.
But for 2 days some of the entities tell me that they are not available, while others are not. Someone with the same problem of loss of entities.

**Comment by skagmo** [comment]
@jcsogo You seem to use a different custom component - not ha_vwid.

**Comment by skagmo** [comment]
@javierivi The component only makes one entity, _sensor.state_of_charge_, the rest would be template sensors that you have made from the attributes of _sensor.state_of_charge_. As the API changes, the sensors available and their name as attributes can change, so you'll have to delete or change your template sensors accordingly.

**Comment by jcsogo** [comment]
> @jcsogo You seem to use a different custom component - not ha_vwid.

You're right that the log is from other integration. Sorry about that. However the issue is the same. It looks like that you have to go once to the webpage directed (myvolkswagen.de) and accept the terms. Logout again and re-login and then you will be asked again about your country. After confirming it for the second time, all works again.
