### ISSUE TITLE
Release 2023.3.1 - VWID not working

### ISSUE THREAD

**Issue by sebking1971** [skagmo/ha_vwid#37]
Release 2023.3.1 installed and the integration has stopped working

**Comment by skagmo** [comment]
- Have you tried pulling the latest changes in this repository? There's some changes regarding VW URLs.
- Can you try signing in on myvolkswagen.net to accept new terms and conditions?

If that doesn't work, can you paste the log entries for vwid?

**Comment by mrebbert** [comment]
Hey Skagmo,

i can confirm that this depends on the new terms and conditions. 
After login on myvolkswagen.net, accepting the new terms and conditions (and after restart of HA) i get the data from vw id again.

KR

**Comment by whistlebare** [comment]
Not sure what i'm doing wrong but I installed this and i'm not seeing any sensors related to this integration...I can't find "sensor.state_of_charge" anywhere

**Comment by skagmo** [comment]
Thanks for confirming!
