### ISSUE TITLE
HA 2023.3.2 issues

### ISSUE THREAD

**Issue by nigels0** [skagmo/ha_vwid#38]
Bit of a weird set of errors. Not sure it is anything to do with this integration (probably not) but more due to the crappy VW software:

1. If I change the charging mode, immediately, the integration gets unavailable data
2. to resolve this, I have to log into the ID site again (on a PC - not the ID app), change some contact details in the profile, delete the integration and re-load it. all is working then

Secondly, the switch to charge the car (when the car is set to timer) doesn't work. Again, I'm not sure that this is a VW thing as their logic is that if the car is set to timer, then you shouldn't be able to start charging manually.

There is no option with the API to switch from timer to manual as far as I can see.

**Comment by skagmo** [comment]
Hi. Could it be that you meant to comment on another VWID component for HA? This (ha_vwid) doesn't have support for any kind of control, only readout, so I'm not sure what you mean about changing charging mode.

**Comment by nigels0** [comment]
Not true, I can start and stop the car charging with this integration for example.
